# Generated by Django 3.2.8 on 2021-11-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_usuarios', '0002_auto_20211107_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_nac',
            field=models.DateField(default='2018-07-22'),
        ),
    ]
