# Generated by Django 2.2.5 on 2021-12-05 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('foto', models.ImageField(default='albumes/default.jpg', upload_to='albumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=50)),
                ('seguidores', models.IntegerField(default=0)),
                ('verificacion', models.BooleanField(default=False)),
                ('foto', models.ImageField(default='artistas/default.jpg', upload_to='artistas/')),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.CharField(max_length=50)),
                ('reproducciones', models.IntegerField(default=0)),
                ('duracion', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
                ('fk_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_musica.Albumes')),
                ('fk_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_musica.Generos')),
            ],
        ),
        migrations.AddField(
            model_name='albumes',
            name='fk_artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_musica.Artistas'),
        ),
    ]
