# Generated by Django 3.2.8 on 2021-11-08 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Artistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artista', models.CharField(max_length=50)),
                ('seguidores', models.IntegerField()),
                ('verificacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Canciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.CharField(max_length=50)),
                ('reproducciones', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('fk_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_musica.albumes')),
                ('fk_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_musica.generos')),
            ],
        ),
        migrations.AddField(
            model_name='albumes',
            name='fk_artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_musica.artistas'),
        ),
    ]
