# Generated by Django 3.2.8 on 2021-11-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_musica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistas',
            name='seguidores',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='canciones',
            name='reproducciones',
            field=models.IntegerField(default=0),
        ),
    ]
