# Generated by Django 3.2.8 on 2021-11-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_musica', '0003_auto_20211112_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generos',
            name='genero',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
