# Generated by Django 3.2.8 on 2021-11-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_musica', '0004_alter_generos_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='canciones',
            name='link',
            field=models.CharField(default='https://open.spotify.com/track/6pq7EtEDWgD5Sh02RJaXK7?si=6deb17433e464bc3', max_length=200),
        ),
    ]
