# Generated by Django 3.2.8 on 2021-11-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_musica', '0005_canciones_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canciones',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
